#!bin/bash/ -e

if git status --porcelain 2>/dev/null | grep -q .; then
  echo "Working copy is dirty" >&2
  exit 1
fi

grunt wbb:html
git checkout gh-pages
rm -rf images && rm index.html && rm main.min.css
cd builds/html
cp -r * ../../
cd ../../
rm -rf builds
git add .
git commit -m "Automatic gh-pages commit."
git checkout master
